services:
  php:
    build:
      context: ./php81
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    container_name: dev-php81
    restart: unless-stopped
    volumes:
      - ${PROJETOS_PATH}:/var/www
      - ./docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini:ro
      - ./openssl.cnf:/etc/ssl/openssl.cnf:ro
    networks:
      - dev-network
    tty: true
    extra_hosts:
      - executiva.test:127.0.0.1

  nginx:
    build: ./nginx
    container_name: dev-nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ${PROJETOS_PATH}:/var/www
      - ./nginx/sites:/etc/nginx/conf.d:ro
    networks:
      - dev-network
    depends_on:
      - php
    tty: true

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    container_name: dev-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dev}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
